[package]
name = "image_sharing"
version = "1.0.0"
authors = []

[addresses]
my_addrx='34f794d32982b9ca7f69de995ab620196f8f8f5961c3405fac9665a3d14139b9'
[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
