[package]
name = "image_sharing"
version = "1.0.0"
authors = []

[addresses]
my_addrx='ebf510766c64cfade3f8f1875163bd885b4db22b249fda2439c9bc529ceb3692'
[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
